---
title: "BGGN213_Class14"
author: "Yutao Wen"
date: "5/17/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(BiocManager)
library(DESeq2)
library("AnnotationDbi")
library("org.Hs.eg.db")
```

```{r}
counts <- read.csv("airway_scaledcounts.csv", stringsAsFactors = FALSE)
metadata <- read.csv("airway_metadata.csv", stringsAsFactors = FALSE)
View(counts)
View(metadata)
```

Q1. How many genes are in this dataset?
```{r}
nrow(counts)
```

Q2. How many 'control' cell lines do we have?
```{r}
table(metadata$dex)
```

Check if col title of counts is the same with the row names of the metadata
```{r}
colnames(counts)
```

```{r}
metadata$id
```

```{r}
all(colnames(counts)[-1] == metadata$id)
```

```{r}
control <- metadata[metadata$dex == "control",]
control.mean <- rowSums(counts[,control$id])/length(control$id)
head(control.mean)
names(control.mean) <- counts$ensgene
```

```{r}
treated <- metadata[metadata$dex == "treated",]
treated.mean <- rowSums(counts[,treated$id])/length(treated$id)
head(treated.mean)
names(treated.mean) <- counts$ensgene
```

```{r}
mean.counts <- data.frame(control.mean, treated.mean)
head(mean.counts)
```

```{r}
plot(mean.counts)
plot(log(mean.counts))
# or add argument "log="xy""
```

```{r}
log2fc <- log2(mean.counts$treated.mean/mean.counts$control.mean)
mean.counts <- data.frame(mean.counts, log2fc)
head(mean.counts)
```

NaN? When 0 is divided by 0
Remove zero expression of the treated and control from data set
```{r}
zero.values <- unique(which(mean.counts[,1:2] == 0, arr.ind = TRUE)[,1])
my.counts <- mean.counts[-zero.values,]
```

```{r}
up.ind <- my.counts[my.counts$log2fc > 2,]
nrow(up.ind)
down.ind <- my.counts[my.counts$log2fc < -2,]
nrow(down.ind)
```

Add annotation data

```{r}
anno <- read.csv("annotables_grch38.csv")
```

```{r}
mycounts.anno <- merge(x=my.counts, y=anno, by.x="row.names", by.y="ensgene")
```



```{r}
mycounts.anno$symbol <- mapIds(org.Hs.eg.db,
                     keys=mycounts.anno$Row.names, # Our genenames
                     keytype="ENSEMBL",        # The format of our genenames
                     column="SYMBOL",          # The new format we want to add
                     multiVals="first")
mycounts.anno$uniprot <- mapIds(org.Hs.eg.db,
                     keys=mycounts.anno$Row.names, # Our genenames
                     keytype="ENSEMBL",        # The format of our genenames
                     column="UNIPROT",          # The new format we want to add
                     multiVals="first")
mycounts.anno$entrez <- mapIds(org.Hs.eg.db,
                     keys=mycounts.anno$Row.names, # Our genenames
                     keytype="ENSEMBL",        # The format of our genenames
                     column="ENTREZID",          # The new format we want to add
                     multiVals="first")
```

```{r}
citation("DESeq2")
```

Build our data set
```{r}
dds <- DESeqDataSetFromMatrix(countData=counts, 
                              colData=metadata, 
                              design=~dex, 
                              tidy=TRUE)
dds <- DESeq(dds)
```

```{r}
res <- results(dds)
```

```{r}
summary(res)
```

```{r}
res05 <- results(dds, alpha = 0.05)
summary(res05)
```

```{r}
mycols <- rep("gray", nrow(res))
mycols[res$padj<0.05] <- "red"
mycols[res$padj<0.05 & abs(res$log2FoldChange)>2] <- "blue"

plot( res$log2FoldChange,  -log(res$padj), col=mycols, abline(h=-log(0.05), v=c(-2,2), col="darkgray", lty=2),xlab="Log2(FoldChange)",
      ylab="-Log(P-value)")
```

```{r}
x <- as.data.frame(res)
x$symbol <- mapIds(org.Hs.eg.db, 
                   keys=row.names(x),
                   keytype="ENSEMBL",
                   column="SYMBOL",
                   multiVals="first")
```

```{r}
library(EnhancedVolcano)
EnhancedVolcano(x,
    lab = x$symbol,
    x = 'log2FoldChange',
    y = 'pvalue')
```

